import React from "react";
import * as Icon from "react-feather";
const navigationConfig = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/",
  },
  {
    type: "groupHeader",
    groupTitle: "Component",
  },
  {
    id: "users",
    title: "Users ",
    type: "collapse",
    icon: <Icon.User size={20} />,
    children: [
      {
        id: "usersList",
        title: "Users List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/users/usersList",
      },
    ],
  },
  {
    id: "script",
    title: "Script ",
    type: "collapse",
    icon: <Icon.User size={20} />,
    children: [
      {
        id: "scriptList",
        title: "Script List",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/script/scriptList",
      },
    ],
  },
  {
    id: "trade",
    title: "Trade",
    type: "collapse",
    icon: <Icon.Users size={20} />,
    children: [
      {
        id: "allTradeList",
        title: "All Trade",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/trade/allTradeList",
      },
      {
        id: "fNoIndexList",
        title: "FNO Index",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/trade/fNoIndexList",
      },
      {
        id: "fNoEquityList",
        title: "FNO Equity",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/trade/fNoEquityList",
      },
      {
        id: "equityCashList",
        title: "Equity Cash",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/trade/equityCashList",
      },
    ],
  },
  {
    id: "packagePlanList",
    title: "Package Plan",
    type: "item",
    icon: <Icon.User size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/package/packagePlanList",
  },
  {
    id: "paidServeiceList",
    title: "Paid Serveice Content",
    type: "item",
    icon: <Icon.User size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/premium/paidServeiceList",
  },
  {
    id: "faqList",
    title: "FAQ",
    type: "item",
    icon: <Icon.User size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/app/faq/faqList",
  },
  {
    id: "notification",
    title: "Notification",
    type: "collapse",
    icon: <Icon.User size={20} />,
    children: [
      {
        id: "notificationList",
        title: "Notification List ",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/notification/notificationList",
      },
    ],
  },
  {
    id: "subplan",
    title: "Subscription ",
    type: "collapse",
    icon: <Icon.User size={20} />,
    children: [
      {
        id: "SubPlanVideos",
        title: "Plan Video ",
        type: "item",
        icon: <Icon.Circle size={12} />,
        permissions: ["admin", "editor"],
        navLink: "/app/subplan/SubPlanVideos",
      },
    ],
  },
  {
    id: "feedbackList",
    title: "Feedback List ",
    type: "item",
    icon: <Icon.Circle size={12} />,
    permissions: ["admin", "editor"],
    navLink: "/app/feedback/feedbackList",
  },
  {
    id: "pageSetUP",
    title: "Page SetUp",
    type: "collapse",
    icon: <Icon.User size={20} />,
    children: [
      {
        id: "aboutus",
        title: "About Us ",
        type: "item",
        icon: <Icon.User size={20} />,
        permissions: ["admin", "editor"],
        navLink: "/app/pageSetUP/about/AllaboutUs",
      },
      {
        id: "helpUs",
        title: "Help Us",
        type: "item",
        icon: <Icon.User size={20} />,
        permissions: ["admin", "editor"],
        navLink: "/app/pageSetUP/helpUs/HelpUs",
      },

      {
        id: "TermConditionList",
        title: "Term And Condition ",
        type: "item",
        icon: <Icon.User size={20} />,
        permissions: ["admin", "editor"],
        navLink: "/app/pageSetUP/termscondition/TermConditionList",
      },
    ],
  },
];
export default navigationConfig;
